.eslintrc.cjs, .vscode/settings.json, package-lock.json, package.json, src/lib/button/Button.svelte, src/lib/card/Card.svelte, src/lib/divider/Divider.svelte, src/lib/fieldset/FieldSet.svelte, src/lib/index.js, src/lib/key/Key.svelte, src/lib/spacer/Spacer.svelte, src/lib/text/Text.svelte, src/lib/toggle/Toggle.svelte, src/lib/types.ts, src/lib/utils/Loading.svelte, src/routes/+page.svelte
Going to open with some more components.
- Text
- Card
- Spacer
- Divider
- Toggled
- FieldSet
- Key
Still lots of work to get this to something close to a UI library
=> More components branch

README.md, package-lock.json, package.json, src/app.css, src/lib/checkbox/Checkbox.svelte, src/routes/+page.svelte
- Fixes #7
- Added disabled behavior for Checkbox
- Made checkbox more accessible with label
=> Quick Fixes

package.json, src/app.css, src/lib/button/Button.svelte, src/lib/index.js, src/lib/input/Input.svelte, src/lib/modal/Modal.svelte, src/lib/textarea/TextArea.svelte, src/routes/+page.svelte
Opening this before I add some heavier components that may take longer
=> More components

.github/workflows/continuous-deployment.yml, .github/workflows/contiunous-integration.yml, package-lock.json, package.json
- Testing CD first run should fail
=> Package version CD check

package-lock.json, package.json, src/lib/checkbox/Checkbox.svelte, src/lib/icons/CheckMarkIcon.svelte, src/lib/icons/ChevronIcon.svelte, src/lib/icons/CloneIcon.svelte, src/lib/select/Select.svelte, src/lib/snippet/Snippet.svelte, src/routes/+page.svelte
- Fixes #15 
- Icons now use "currentColor" allowing them to be set by parent element text color 
- Snippets are now complete with copying and colors
- Had to modify components consuming icons (Select, Checkbox) to set the text color
=> Icons branch

package-lock.json, package.json, src/lib/button/Button.svelte, src/lib/index.js, src/routes/+page.svelte
- Added anchor element option to button
=> Component refining

package-lock.json, package.json, src/app.css, src/lib/index.js, src/lib/tabs/TabItem.svelte, src/lib/tabs/Tabs.svelte, src/routes/+page.svelte
=> Tabs Component

package-lock.json, package.json, src/lib/details/Details.svelte, src/routes/components/header/+page.svelte, src/routes/components/hero/+page.svelte
Fixes #32 
Fixes #33 
- Also fixes centering issue with hero docs example
=> Complete docs branch

package-lock.json, package.json, src/lib/select/Select.svelte, src/lib/tabs/Tabs.svelte, src/routes/components/+layout.svelte, src/routes/components/tabs/+page.svelte
- Added documentation for tabs
- Fixed an issue with the width of the select component
=> Tabs documentation and component fixes

.github/workflows/continuous-deployment.yml, .github/workflows/contiunous-integration.yml, package.json
- This should allow anyone to run workflows without interuption
=> Removed tokens from runs

package.json, src/lib/code/Code.svelte, src/lib/types.ts, src/routes/components/code/+page.svelte, src/routes/guide/installation/+page.svelte
- Added line numbers
- Added edit highlights
=> Code improvements branch

src/routes/components/code/+page.svelte
=> Changed language in docs to sql

package.json, src/lib/details/Details.svelte, src/lib/input/Input.svelte, src/lib/key/Key.svelte, src/lib/modal/Modal.svelte, src/routes/components/code/+page.svelte, src/routes/components/details/+page.svelte, src/routes/components/drawer/+page.svelte, src/routes/components/dropdown/+page.svelte, src/routes/components/header/+page.svelte, src/routes/components/hero/+page.svelte, src/routes/components/key/+page.svelte, src/routes/components/modal/+page.svelte, src/routes/components/page/+page.svelte, src/routes/components/search/+page.svelte, src/routes/components/spacer/+page.svelte
- Completed all the missing docs
- Search, Key, Modal, Page, Drawer, Details, Dropdown
- Fixes #51
=> Final docs branch

package.json, src/lib/header/Header.svelte, src/lib/hero/Hero.svelte, src/routes/components/header/+page.svelte, src/routes/components/hero/+page.svelte
- Fixes #67 
- Adds `exclusionHeight` property to hero to allow you to subtract things like the header height from the height of the hero
=> Header Features

package-lock.json, package.json, src/lib/text/Text.svelte, src/routes/components/text/+page.svelte
=> Text responsiveness branch

src/lib/input/Input.svelte, src/routes/components/input/+page.svelte
=> Input fixes branch

src/lib/docs-components/nav-route/NavRoute.svelte, src/routes/components/+layout.svelte, src/routes/guide/+layout.svelte
100th branch updating a simple light mode ..i mean i m dumb right now
=> final update light-mode 

.eslintrc.cjs, package.json, src/lib/index.js, src/lib/skeleton/Skeleton.svelte, src/lib/skeleton/SkeletonContainer.svelte, src/routes/components/+layout.svelte, src/routes/components/skeleton/+page.svelte
- Added Skeleton and SkeletonContainer component
=> Added skeleton component

package.json, src/lib/code/Code.svelte
- Fixed issue where the copy button would scroll with the content and the numbers would scoll with the content
=> Fixed horizontal scrolling with code

package.json, src/lib/tabs/TabItem.svelte
- This should make it possible to use without sveltekit fixing #89
=> Removed Svelte-Kit dependency

package.json, src/lib/input/Input.svelte, src/routes/components/input/+page.svelte
- Fixes #86
- Also made some style adjustments to make inputs look better
=> Added sizing

src/lib/docs-components/nav-route/NavRoute.svelte, src/lib/input/Input.svelte, src/routes/components/+layout.svelte, src/routes/components/input/+page.svelte, src/routes/guide/+layout.svelte
This indicates to the user what section they are in
=> Section now turns blue when active

src/routes/components/skeleton/+page.svelte
- Added another example to /components/skeleton
=> Skeleton examples branch

package-lock.json, package.json, src/routes/guide/installation/+page.svelte
Fixes #100
Users will need to downgrade to Tailwind 3.4.0 until we upgrade to 3.4.1
=> Fixes #100

package-lock.json, package.json, src/lib/radiotabs/RadioTabs.svelte, src/lib/skeleton/SkeletonContainer.svelte, src/routes/components/skeleton/+page.svelte, src/routes/guide/dark-mode/+page.svelte, src/routes/guide/installation/+page.svelte
- Fixes #104 
- Fixes #106 
No breaking changes
=> Features branch

package-lock.json, package.json, src/lib/search/Search.svelte, src/lib/select/Select.svelte, src/routes/components/search/+page.svelte, src/routes/components/select/+page.svelte
- Fixes #115 
- Fixes #121
No breaking changes! yay!
=> Fixes #115 and #121

package-lock.json, package.json, src/lib/index.js
=> Fixes #126

package.json, src/lib/checkbox/Checkbox.svelte, src/lib/code/Code.svelte, src/lib/details/Details.svelte, src/lib/input/Input.svelte, src/lib/lightswitch/LightSwitch.svelte, src/lib/radiotabs/RadioTab.svelte, src/lib/search/Search.svelte, src/lib/select/Option.svelte, src/lib/select/Select.svelte, src/lib/snippet/Snippet.svelte, src/lib/tabs/TabItem.svelte, src/lib/toggle/Toggle.svelte
=> Added type="button"

package-lock.json, package.json, src/lib/button/Button.svelte, src/lib/checkbox/Checkbox.svelte, src/lib/input/Input.svelte, src/lib/search/Search.svelte, src/lib/toggle/Toggle.svelte, src/routes/components/search/+page.svelte
- Fixes #133 
- Fixes #132 
- Fixes #131 
- Fixes #130 
No breaking changes
=> Fixes branch

package-lock.json, package.json, src/lib/input/Input.svelte, src/routes/components/input/+page.svelte
- Added colors to input with `Color` attribute Fixes #136 
None
=> Fixes #136

package.json, src/lib/tabs/Tabs.svelte, src/routes/components/+layout.server.ts, src/routes/components/+page.svelte
- Fixes #149 
- Moves redirect for components to server-side
Not huge but removed default padding applied to the tabs component
=> Improvements branch

package-lock.json, package.json, src/lib/button/Button.svelte, src/lib/checkbox/Checkbox.svelte, src/lib/header/Header.svelte, src/lib/index.js, src/lib/input/Input.svelte, src/lib/label/Label.svelte, src/lib/search/Search.svelte, src/lib/select/Option.svelte, src/lib/select/Select.svelte, src/lib/textarea/TextArea.svelte, src/lib/togglebutton/ToggleButton.svelte, src/routes/components/+layout.svelte, src/routes/components/button/+page.svelte, src/routes/components/checkbox/+page.svelte, src/routes/components/header/+page.svelte, src/routes/components/input/+page.svelte, src/routes/components/label/+page.svelte, src/routes/components/select/+page.svelte, src/routes/components/textarea/+page.svelte, src/routes/components/togglebutton/+page.svelte
- Fixes #164 
- Fixes #165 
- Fixes #163 
- Fixes #162 
- Fixes #160 
- Fixes #158 
- Fixes #157 
- Fixes #155 
- This also adds a bunch of documentation
No breaking changes
=> Component Fixes

.eslintrc.cjs, package.json, src/lib/docs-components/arrow-navigation/ArrowNavigation.svelte, src/lib/index.js, src/lib/ipaddressinput/IPAddressInput.svelte, src/lib/util/ip-address.ts, src/routes/components/+layout.svelte, src/routes/components/ipaddressinput/+page.svelte, src/routes/components/toggle/+page.svelte
- Adds new `IPAddressInput`
None
=> IPAddressInput Addition

package-lock.json, package.json, src/lib/snippet/Snippet.svelte, src/lib/util/utils.ts
- Refactors Snippet component to use twMerge, clsx, and cva as mentioned in #170 as a proof of content
- Signifigantly reduces the amount of tailwind classes in the browser making things more readable
- Should also reduce style conflicts
Before:
After:
None
=> Tw refactor branch

package.json, src/lib/badge/Badge.svelte, src/lib/button/Button.svelte, src/lib/card/Card.svelte, src/lib/checkbox/Checkbox.svelte, src/lib/header/Header.svelte, src/lib/lightswitch/LightSwitch.svelte, src/lib/snippet/Snippet.svelte, src/lib/text/Text.svelte, src/lib/toggle/Toggle.svelte, src/routes/components/badge/+page.svelte, src/routes/components/card/+page.svelte, src/routes/components/checkbox/+page.svelte, src/routes/components/text/+page.svelte
- Massively reducing the amount of characters in the styles
- Makes things much easier to understand
- Did a few more components
- Badge component changed massively in styling
- Removed `proportional` from Button
- Removed `style` from text
=> CVA Refactor

package-lock.json, package.json, src/lib/select/Select.svelte, src/lib/util/to-array.ts, src/routes/components/select/+page.svelte
- Adds `multiSelect` attribute to **Select** component for multi-select functionality
No breaking changes
=> Fixes #134

package.json, src/lib/select/Select.svelte, src/routes/components/select/+page.svelte
- Fixes #176
- Select now reacts to change in value
- Select now reacts to change in list items
- Select change event fires correctly for multi-select
Removes value from changed event may re-add later
-   [ ] My code is up to date with main
-   [ ] My code requires a new package version to be created
-   [ ] I have updated the package version
=> Fixes #176

package.json, src/lib/dropdown/Dropdown.svelte, src/routes/components/dropdown/+page.svelte
Improvements to make it easier to work with dropdown and make it usable in lists where its not possible to use references.
- Added query selector option to anchor
- Added custom events to fire from anchor
None
=> Drop Down Improvements

package.json, src/lib/icons/GridIcon.svelte, src/lib/icons/ListIcon.svelte, src/lib/index.js, src/lib/ipaddressinput/IPAddressInput.svelte, src/lib/types.ts, src/lib/util/ip-address.ts, src/routes/components/icons/+page.svelte
- Adds grid icon and list icon
- Fixes #184 
None
=> Fixes #184

.eslintrc.cjs, package.json, src/lib/breadcrumbs/BreadCrumbs.svelte, src/lib/breadcrumbs/BreadCrumbsDemo.svelte, src/lib/index.js, src/routes/components/+layout.svelte, src/routes/components/breadcrumbs/+page.svelte
- Adds breadcrumbs component
None
=> Adds Breadcrumbs component

package.json, src/app.css, src/lib/drawer/Drawer.svelte, src/lib/dropdown/Dropdown.svelte, src/lib/modal/Modal.svelte, src/lib/page/Page.svelte, src/lib/select/Option.svelte, src/lib/select/Select.svelte, src/lib/text/Text.svelte, src/lib/util/find-child.ts, src/routes/components/dropdown/+page.svelte
- Fixes #207 
- Fixes #205 
- Adds lockScroll attribute to dropdown and select off by default and updated the docs
None
=> More improvements

package-lock.json, package.json, src/lib/select/Option.svelte, src/lib/select/Select.svelte, src/lib/tabs/TabItem.svelte, src/lib/tabs/Tabs.svelte, src/routes/components/select/+page.svelte, src/routes/components/tabs/+page.svelte
- Fixes #212 
- Fixes #210 
- Fixes #209 
- Fixes #203 
- Adds auto scrolling when using arrow keys on select input
- Changes height of tabs slightly from 46px to 44px
=> More Fixes and improvements

package-lock.json, package.json, src/lib/tabs/Tabs.svelte
- Border was not properly following the selected tab this has been fixed
None
=> Fixes issue with tabs border

package.json, src/lib/tabs/Tabs.svelte
- Fixes #218 adding effect to $page
None
=> Should Fix #218

package.json, src/lib/tabs/Tabs.svelte
Reverts ieedan/geist-ui-svelte#226
=> Revert "Should Fix #218"

package-lock.json, package.json, src/lib/ipaddressinput/IPAddressInput.svelte
- Adds . functionality to the IPAddress input
None
-   [ ] My code is up to date with main
=> Adds . functionality to the IPAddress input

package.json, src/lib/modal/Modal.svelte
- Adds vertical responsiveness to modal component
None
=> Responsive modal

src/routes/components/loading/+page.svelte
Fixed a typo in the loading component (import statement from Divider to Loading)
-   [ ] My code requires a new package version to be created
-   [ ] I have updated the package version
=> Fixed a typo in the loading component (import statement from Divider to Loading)

package-lock.json, package.json, src/lib/tabs/Tabs.svelte
=> Fixes #239

package-lock.json, package.json, src/lib/breadcrumbs/BreadCrumbs.svelte, src/lib/breadcrumbs/BreadCrumbsDemo.svelte, src/lib/tabs/TabItem.svelte
- Changed color of tabs component inactive state to match other inactive states
- Updated the separator styling for the bread crumb component
Just changes to the look
=> Updated text colors and styles for tabs and breadcrumbs

src/routes/components/input/+page.svelte
- Forgot to add this in the last PR just fixes a visual bug on the input docs screen
-   [ ] My code requires a new package version to be created
-   [ ] I have updated the package version
=> Fix issue with input screen

src/routes/components/fieldset/+page.svelte
- fixes #246
None
-   [ ] My code requires a new package version to be created
-   [ ] I have updated the package version
=> fixes #246

src/routes/components/fieldset/+page.svelte
Reverts ieedan/geist-ui-svelte#249
=> Revert "fixes #246"

package.json, src/lib/hero/Hero.svelte, src/routes/components/hero/+page.svelte
=> Add true center

package-lock.json, package.json, src/lib/select/Select.svelte
Now typing a character into a select will select the first option starting with that character
None
=> Improved `<Select/>`

package-lock.json, package.json, src/lib/select/Select.svelte
- Fixes issue with `readonly` on `<Select/>` component
- Also bumps dependencies
None
=> Fixes #256

package-lock.json, package.json, src/lib/avatar/Avatar.svelte
- Fixes issue where image would not be circular if a rectangular image was provided
- Updated dependencies
None
=> Avatar Fixes

package-lock.json, package.json, src/lib/textarea/TextArea.svelte, src/routes/components/textarea/+page.svelte
- Also properly adds class to twMerge
- Possible breaking change by classes now properly applying thanks to `twMerge`
=> feat: Adds `resize` and `autoResize` to `<TextArea/>`
